version: "2.4"

#This docker-compose file contains utility containers not vital for the working of the web application, such as an orchestrator manager (portainer) and a continuous integration app (drone)

services:

  portal:
    build:
      context: ./$PATH_OMS_GLOBAL/portal/
      dockerfile: ./Dockerfile.dev
    image: aegee/portal:dev
    restart: always
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portal"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${SUBDOMAIN_PORTAL}${BASE_URL}"
      - "traefik.frontend.priority=20"

secrets:
    jwt_key:
        file: secrets/jwt_key
    sendgrid_key:
        file: secrets/sendgrid_key
    mail_user:
        file: secrets/sendgrid_key
    mail_password:
        file: secrets/sendgrid_key
    db_password:
        file: secrets/core-db_password

networks:
  default:
    external:
      name: OMS
