version: "3.2"

# oms-global: traefik, cachet, swagger
# oms-utils: wiki, forum, survey
# oms-dev: portainer, pgadmin, mongoadmin,...
services:

### Proxy container #######################################

    traefik:
        image: traefik:v1.7.4-alpine
        restart: always #or unless-stopped? TODO: decide
        command: --web.metrics.prometheus
        ports:
          - 80:80
          - 443:443
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./secrets/acme.json:/etc/acme.json #we have to mount it, so no secrets
          - ./$PATH_OMS_GLOBAL/traefik/logs:/var/log/traefik/
          - ./$PATH_OMS_GLOBAL/traefik/traefik.toml:/etc/traefik/traefik.toml
          #- shared_logs:/var/log/traefik/
#        networks:
#          - management
        labels:
          - traefik.enable=true
          - traefik.backend=traefik
          - traefik.port=8080
          - traefik.frontend.rule=Host:${SUBDOMAIN_TRAEFIK}${BASE_URL}
          - traefik.frontend.priority=20
          - traefik.frontend.auth.basic.users=admin:${PW_TRAEFIK}


#volumes:
#   shared_logs:
#       driver: "local"
#   upload:


networks:
  default:
    external:
      name: OMS
