version: "3.2"

services:

### Statuspage (Cachet) Container #######################################

    maria-statuspage:
      image: mariadb:10.4
      restart: always
      environment:
        MYSQL_DATABASE: "cachet"
        MYSQL_USER: "cachet"
        MYSQL_PASSWORD: "5ecr3t"
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      volumes:
        - database:/var/lib/mysql

    statuspage:
      restart: always
      # build:
      #   context: ./$PATH_OMS_GLOBAL/cachet
      #   dockerfile: ./docker/app/Dockerfile
      image: aegee/statuspage:latest
      env_file: ./$PATH_OMS_STATUS/cachet/.env
      #volumes:
      #  - ./$PATH_OMS_STATUS/cachet/.env:/app/.env:rw
      depends_on:
        - maria-statuspage
        - redis-statuspage-cache


    nginx-statuspage:
      restart: always
      # build:
      #   context: ./$PATH_OMS_GLOBAL/cachet
      #   dockerfile: ./docker/nginx/Dockerfile
      image: aegee/nginx-statuspage:latest
      depends_on:
        - statuspage
      expose:
        - 8080
      labels:
        - traefik.enable=true
        - traefik.backend=nginx-statuspage
        - traefik.port=8080
        - traefik.frontend.rule=Host:${SUBDOMAIN_STATUSPAGE}${BASE_URL}
        - traefik.frontend.priority=20

    redis-statuspage-cache:
      restart: unless-stopped
      image: redis:5-alpine

volumes:
  database:
    driver: local

networks:
  default:
    external:
      name: OMS

