version: '3.2'

services:

  elasticsearch:
    build:
      context: ./$PATH_OMS_ELASTIC/elasticsearch/
      args:
        ELK_VERSION: 6.4.2
    volumes:
      - ./$PATH_OMS_ELASTIC/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk

  logstash:
    build:
      context: ./$PATH_OMS_ELASTIC/logstash/
      args:
        ELK_VERSION: 6.4.2
    volumes:
      - ./$PATH_OMS_ELASTIC/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./$PATH_OMS_ELASTIC/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./$PATH_OMS_ELASTIC/kibana/
      args:
        ELK_VERSION: 6.4.2
    volumes:
      - ./$PATH_OMS_ELASTIC/kibana/config/:/usr/share/kibana/config:ro
    ports:
        - 5601:5601
#    networks:
#      - elk
    depends_on:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.backend=kibana
      - traefik.frontend.rule=Host:${SUBDOMAIN_KIBANA}${BASE_URL}
      - traefik.ports=5601
      - traefik.frontend.priority=20
      - traefik.frontend.auth.basic=admin:$$2y$$05$$nO3b1XapOtAORGcLAwMmyenyrVU4xWuEk08nEwvmFRcABz1NSv4Xq

#  dockbeat:
#    image: ingensi/dockbeat:latest #they have no fixed tags
#    volumes:
#        - /var/run/docker.sock:/var/run/docker.sock:ro
#        - ./$PATH_OMS_ELASTIC/dockbeat/:/etc/dockbeat
#    #    networks:
#    #      - elk
#    depends_on:
#      - logstash

#   metricbeat:
#     #image: docker.elastic.co/beats/metricbeat:6.4.2
#     build:
#       context: ./$PATH_OMS_ELASTIC/metricbeat/
#     volumes:
#         - /var/run/docker.sock:/var/run/docker.sock:ro
#         - /proc/:/hostfs/proc:ro
#         - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#         - /:/hostfs/:ro
#     #- ./$PATH_OMS_ELASTIC/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
#     environment:
#         - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601" # logstash:5044"
#         - "HOST_ELASTICSEARCH=elasticsearch:9200"
#     command: -system.hostfs=/hostfs -e
#     network_mode: host
#     extra_hosts:
#         - "elasticsearch:172.17.0.1" # The IP of docker0 interface to access host from container
#         - "logstash:172.17.0.1" # The IP of docker0 interface to access host from container
#         - "kibana:172.17.0.1" # The IP of docker0 interface to access host from container
# #    networks:
# #        - elk
#     depends_on:
#         - logstash

#   filebeat:
#     #image: docker.elastic.co/beats/metricbeat:6.4.2
#     build:
#       context: ./$PATH_OMS_ELASTIC/filebeat/
#     volumes:
#         - /opt/backups:/opt/backups:ro #MAKE A VOLUME SHARED AMONG CONTAINERS
#           #- shared_logs:/var/log/traefik/ #not this way :/
#         - ./$PATH_OMS_GLOBAL/traefik/logs:/var/log/traefik #not this way :/
#         - ./$PATH_OMS_ELASTIC/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
#           #- ./$PATH_OMS_ELASTIC/filebeat/jesus.yml:/usr/share/filebeat/jesus.yml #just to bring stuff from the container to the host
#           #- ./$PATH_OMS_ELASTIC/filebeat/fields.yml:/usr/share/filebeat/fields.yml
#     environment:
#         - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
#         - "HOST_ELASTICSEARCH=elasticsearch:9200"
#     depends_on:
#         - logstash

#   filebeat-auth:
#     #image: docker.elastic.co/beats/metricbeat:6.4.2
#     build:
#       context: ./$PATH_OMS_ELASTIC/filebeat/
#       dockerfile: ./Dockerfile-auth
#     volumes:
#         - /var/log/auth.log:/var/log/auth/auth.log:ro
#           #- ./$PATH_OMS_ELASTIC/filebeat/filebeat-auth.yml:/usr/share/filebeat/filebeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
#     environment:
#         - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
#         - "HOST_ELASTICSEARCH=elasticsearch:9200"
#     depends_on:
#         - logstash

  logspout:
    build:
      context: ./$PATH_OMS_ELASTIC/logspout/
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        ROUTE_URIS: "logstash://logstash:5000"
#    networks:
#      - elk
      # - OMS
    depends_on:
      - logstash
    restart: on-failure

volumes:
  elastic-data:
    driver: local
#  shared_logs:
#    external:
#        name: shared_logs

networks:
  default:
    external:
      name: OMS
#  elk:
#    driver: bridge
