version: '3.2'

services:

  elasticsearch:
    build:
      context: ./$PATH_OMS_ELASTIC/elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: aegee/elasticsearch:${ELK_VERSION}
    volumes:
      - ./$PATH_OMS_ELASTIC/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  curator:
    build:
      context: ./$PATH_OMS_ELASTIC/elasticsearch/curator/
    image: aegee/elasticsearch-curator:${ELK_VERSION}
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      CRON: 0 0 * * *
      CONFIG_FILE: /usr/share/curator/config/curator.yml
      COMMAND: /usr/share/curator/config/delete_log_files_curator.yml
      UNIT_COUNT: 2
    depends_on:
      - elasticsearch

  logspout:
    build:
      context: ./$PATH_OMS_ELASTIC/logspout/
    image: aegee/logspout:${ELK_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: "logstash://logstash:5000"
      LOGSTASH_TAGS: docker-elk
    depends_on:
      - logstash
    restart: on-failure

  logstash:
    build:
      context: ./$PATH_OMS_ELASTIC/logstash/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: aegee/logstash:${ELK_VERSION}
    volumes:
      - ./$PATH_OMS_ELASTIC/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./$PATH_OMS_ELASTIC/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./$PATH_OMS_ELASTIC/kibana/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: aegee/kibana:${ELK_VERSION}
    volumes:
      - ./$PATH_OMS_ELASTIC/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
        - 5601:5601
    depends_on:
      - elasticsearch
    labels:
      - traefik.enable=true
      - traefik.backend=kibana
      - traefik.frontend.rule=Host:${SUBDOMAIN_KIBANA}${BASE_URL}
      - traefik.ports=5601
      - traefik.frontend.priority=20
      - traefik.frontend.auth.basic=admin:$$2y$$05$$nO3b1XapOtAORGcLAwMmyenyrVU4xWuEk08nEwvmFRcABz1NSv4Xq

#  dockbeat: #INCREDIBLE HOW FUCKING USELESS
#    image: ingensi/dockbeat:latest #they have no fixed tags
#    volumes:
#        - /var/run/docker.sock:/var/run/docker.sock:ro
#        - ./$PATH_OMS_ELASTIC/dockbeat/:/etc/dockbeat
#    depends_on:
#      - logstash

#   metricbeat: #REPLACED BY GRAFANA???
#     build:
#       context: ./$PATH_OMS_ELASTIC/metricbeat/
#       args:
#         ELK_VERSION: 6.4.2
#     #image: docker.elastic.co/beats/metricbeat:6.4.2
#     image: aegee/metricbeat:6.4.2
#     volumes:
#         - /var/run/docker.sock:/var/run/docker.sock:ro
#         - /proc/:/hostfs/proc:ro
#         - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#         - /:/hostfs/:ro
#     #- ./$PATH_OMS_ELASTIC/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
#     environment:
#         - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601" # logstash:5044"
#         - "HOST_ELASTICSEARCH=elasticsearch:9200"
#     command: -system.hostfs=/hostfs -e
#     network_mode: host
#     extra_hosts:
#         - "elasticsearch:172.17.0.1" # The IP of docker0 interface to access host from container
#         - "logstash:172.17.0.1" # The IP of docker0 interface to access host from container
#         - "kibana:172.17.0.1" # The IP of docker0 interface to access host from container
#     depends_on:
#         - logstash

  filebeat:
    build:
      context: ./$PATH_OMS_ELASTIC/filebeat/
      args:
        ELK_VERSION: ${ELK_VERSION}
    image: aegee/filebeat:${ELK_VERSION}
    #image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    volumes:
        - /opt/backups:/opt/backups:ro #TODO MAKE A VOLUME SHARED AMONG CONTAINERS instead of this
          #- shared_logs:/var/log/traefik/ #not this way :/
        - ./$PATH_OMS_GLOBAL/traefik/logs:/var/log/traefik #not optimal..
        - ./$PATH_OMS_ELASTIC/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
          #- ./$PATH_OMS_ELASTIC/filebeat/fields.yml:/usr/share/filebeat/fields.yml
    environment:
        - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
        - "HOST_ELASTICSEARCH=elasticsearch:9200"
    depends_on:
        - logstash

#   filebeat-auth: #FIND A BETTER WAY?! auditbeat?
#     #image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
#     build:
#       context: ./$PATH_OMS_ELASTIC/filebeat/
#       dockerfile: ./Dockerfile-auth
#     volumes:
#         - /var/log/auth.log:/var/log/auth/auth.log:ro
#           #- ./$PATH_OMS_ELASTIC/filebeat/filebeat-auth.yml:/usr/share/filebeat/filebeat.yml:ro # only for dev. do NOT override whole directory as the executable is there
#     environment:
#         - "WAIT_FOR_HOSTS=elasticsearch:9200 kibana:5601"
#         - "HOST_ELASTICSEARCH=elasticsearch:9200"
#     depends_on:
#         - logstash


volumes:
  elastic-data:
    driver: local

networks:
  default:
    external:
      name: OMS
