version: "3.2"

services:
  bitwarden:
    image: bitwardenrs/server:latest 
    restart: on-failure
    volumes:
      - ./$PATH_OMS_SECURITY/bw-data/:/data/
    environment:
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${PW_BITWARDEN_ADMINPANEL}
      - DOMAIN=https://${SUBDOMAIN_BITWARDEN}${BASE_URL}
      - LOG_FILE=/data/bitwarden.log
      - ROCKET_LOG=normal #the only thing above this is "critical", no "warning"
      - SHOW_PASSWORD_HINT=false
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_FROM=bitwarden@${BASE_URL}
      - SMTP_FROM_NAME="AEGEE pass manager"
      - SMTP_PORT=587 
      - SMTP_SSL=true 
      - SMTP_USERNAME=${USER_SENDGRID}
      - SMTP_PASSWORD=${PW_SENDGRID}
    labels:
      - traefik.enable=true
      - traefik.backend=bitwarden
      - traefik.port=80
      - traefik.frontend.rule=Host:${SUBDOMAIN_BITWARDEN}${BASE_URL}
      - traefik.frontend.priority=20

networks:
  default:
    external:
      name: OMS
