filebeat.inputs:
- type: log
  enabled: true
  tags: [ "backup_log", "beat" ]
  fields: 
      x_file_type: "backup"
  paths:
      - /opt/backups/*.log
- type: log
  enabled: true
  tags: [ "traefik_log", "beat" ]
  fields: 
      x_file_type: "traefik-access"
  paths:
      - /var/log/traefik/*.log

name: "filebeat-traefik_and_backup-shipper"
  
output:
    logstash: 
        hosts: ["logstash:5044"]
        escape_html: true

setup:
    kibana:
        host: "kibana:5601"
    dashboards:
        enabled: true
    template:
#        overwrite: true
        name: "filebeat-%{[beat.version]}"
        pattern: "filebeat-*"
        #fields: "/usr/share/filebeat/fields.yml"
#logging.to_syslog: true 
#logging.to_files: false
