version: "2.4"

services:
  oms-core-elixir:
    restart: on-failure
    image: aegee/oms-core-elixir:fab
    depends_on:
      - postgres-oms-core-elixir
    expose:
      - "4000"
    labels:
      - "traefik.frontend.rule=PathPrefix:/services/oms-core-elixir/api;PathPrefixStrip:/services/oms-core-elixir/api"
      - "traefik.frontend.priority=101"
      - "traefik.port=4000"
      - "traefik.backend=oms-core-elixir"
      - "traefik.enable=true"
    env_file: ./${PATH_OMS_CORE_ELIXIR}/.env
    secrets:
      - jwt_key
      - sendgrid_key
      - mail_password
      - mail_user
      - db_password


  postgres-oms-core-elixir:
    restart: always
    image: postgres:10.6
    volumes:
      - postgres-oms-core-elixir:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PW_POSTGRES}"

volumes:
  postgres-oms-core-elixir:
    driver: local

networks:
  default:
    external:
      name: OMS
